version: "3.8"

services:
  web:
    build: ./rastreamento-adidas
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - osrm

  osrm:
  build:
    context: .
    dockerfile: Dockerfile.osrm
    ports:
      - "5000:5000"
